version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "3001:443" # HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    networks:
      app-network:
        aliases:
          - host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway" 

  nextjs:
    build:
      context: .
      # args:
      #   NEXT_PUBLIC_BACKEND_LOCAL_API_URL: https://host.docker.internal:3000/api
    container_name: nextjs-app
    command: npm run start
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
